services:
  mysqldb:
    image: mysql:8.0
    container_name: starlink-mysql
    environment:
      - MYSQL_DATABASE=starlink
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - starlink-network
  api:
    build:
      dockerfile: starlink-app.dockerfile
      context: .
    container_name: starlink
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - starlink-network
networks:
  starlink-network:
    driver: bridge